"""Shared colors and typography for the application theme."""

APP_MODE = "light"
COLOR_THEME = "blue"

BG_WINDOW = "#FFFFFF"
BG_SIDEBAR = "#F7F9FC"
BG_SURFACE = "#FFFFFF"
BG_ELEVATED = "#FFFFFF"
BG_TEXTBOX = "#F1F5F9"
BG_CARD = "#E6F7FA"
BG_CANVAS = "#FFFFFF"
BG_DIVIDER = "#D5DEE8"

TEXT_MAIN = "#1F2937"
TEXT_DIM = "#475569"

ACCENT_CYAN = "#0F96A6"
ACCENT_BLUE = "#2563EB"
ACCENT_PURPLE = "#7C3AED"
ACCENT_TEAL = "#0F766E"

BORDER_CYAN = "#0E8C9B"

SUCCESS = "#0F766E"
WARNING = "#D97706"
ERROR = "#B42318"

FONT_TITLE = ("Segoe UI", 15, "bold")
FONT_LABEL = ("Segoe UI", 13)
FONT_SMALL = ("Segoe UI", 12)
FONT_MONO = ("Courier New", 12)